@hostname=http://127.0.0.1
@port=8000
@base={{hostname}}:{{port}}

GET {{base}}

POST {{hostname}}:8000
Content-Type

{
    "name": "Ivan"
}

PUT http://127.0.0.1:{{port}}

DELETE http://127.0.0.1:8000
