@hostname=http://127.0.0.1
@port=8000
@base={{hostname}}:{{port}}

GET {{base}} HTTP/1.1

GET {{base}}/books


POST {{hostname}}:8000/books
Content-Type: application/json
Authentication: 190231239u

{
    "title": "Das parfum",
    "description": "Patrick Süskinds erster Roman",
    "cover_art_image": "arch8oas.jpeg"
}


PUT http://127.0.0.1:{{port}}/books/1
Content-Type: application/json

DELETE http://127.0.0.1:8000/books/1
